server:
  port: 8080
  compression:
    enabled: true
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
graphql:
  servlet:
    mapping: /graphql
    cors-enabled: true
    max-query-depth: 100
    exception-handlers-enabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"
spring:
#  graphql:
#    path: /graphql
#  graphiql:
#    path: /graphiql
#    enabled: false
#  schema:
#    locations: "**/**"
#    schema:
#      file-extensions: .graphqls,.gqls
#      introspection:
#        enabled: true
#      printer:
#        enabled: false
#  websocket:
#    connection-init-timeout: 60s
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.10:3306/jpabegin?serverTimezone=Asia/Seoul
    username: jpauser
    password: jpapass
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          google: # rest: /oauth2/authorization/google
            client-id: 799406859248-l6ed5jg73ltm9o6cndhkt3vem7dr1d7e.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook: # rest: /oauth2/authorization/facebook
            client-id: 969233130725832
            client-secret: 63a83c64762418bbba92ced0ccdd9dd8
            scope:
              - email
              - public_profile
          naver: # rest: /oauth2/authorization/naver
            client-id: oL32PFNqCGiOjegJiKyb
            client-secret: 4vk1KFk9Ja
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver: # 네이버는 oauth2가 provider를 제공하지 않아서 직접 등록해줘야 함
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보 json을 받을 때 response라는 키 값으로 네이버가 리턴
