server:
  port: 6204
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:postgresql://localhost:15432/postgres
      username: yourusername
      password: yourpassword
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      connection-test-query: SELECT 0
      connection-timeout: 10000
      idle-timeout: 10000
      max-lifetime: 420000
      maximum-pool-size: 30
      minimum-idle: 15
      validation-timeout: 10000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": false
        "[generate_statistics]": true
        "[order_by]":
          "[default_null_ordering]": last
        "[show_sql]": false
        "[use_sql_comments]": false
    show-sql: false
  graphql:
    path: /graphql
    schema:
      locations: classpath:graphql/**/
    graphiql:
      enabled: true
logging:
  config: classpath:sl4j-local.xml
jwt:
  secret: GENERATED_KEY_FROM_JavaTests
my:
  aws:
    access-key: ACCESSKEY
    secrete-key: SECRETKEY
    region: ap-northeast-2
    bucket: test-bucket
    s3-url: https://test-bucket.s3.ap-northeast-2.amazonaws.com/
